{
  "comments": [
    {
      "key": {
        "uuid": "d536f4ad_4561495a",
        "filename": "appengine/findit/pipelines/flake_failure/next_commit_position_pipeline.py",
        "patchSetId": 2
      },
      "lineNbr": 69,
      "author": {
        "id": 1157909
      },
      "writtenOn": "2018-05-04T17:42:33Z",
      "side": 1,
      "message": "Assert at the wrong place or on the wrong value? calculated_next_commit_position is None here.",
      "range": {
        "startLine": 69,
        "startChar": 10,
        "endLine": 69,
        "endChar": 41
      },
      "revId": "fa34123fc512360c148f9b840c1b0d3a22ee39da",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c65b0a6f_4a5d3017",
        "filename": "appengine/findit/pipelines/flake_failure/next_commit_position_pipeline.py",
        "patchSetId": 2
      },
      "lineNbr": 95,
      "author": {
        "id": 1157909
      },
      "writtenOn": "2018-05-04T17:42:33Z",
      "side": 1,
      "message": "next_commit_position",
      "range": {
        "startLine": 95,
        "startChar": 40,
        "endLine": 95,
        "endChar": 71
      },
      "revId": "fa34123fc512360c148f9b840c1b0d3a22ee39da",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b06a811e_4cdccd71",
        "filename": "appengine/findit/pipelines/flake_failure/next_commit_position_pipeline.py",
        "patchSetId": 2
      },
      "lineNbr": 126,
      "author": {
        "id": 1157909
      },
      "writtenOn": "2018-05-04T17:42:33Z",
      "side": 1,
      "message": "next_commit_position",
      "range": {
        "startLine": 126,
        "startChar": 38,
        "endLine": 126,
        "endChar": 69
      },
      "revId": "fa34123fc512360c148f9b840c1b0d3a22ee39da",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "46739cdb_b0ec95d9",
        "filename": "appengine/findit/pipelines/flake_failure/next_commit_position_pipeline.py",
        "patchSetId": 2
      },
      "lineNbr": 142,
      "author": {
        "id": 1157909
      },
      "writtenOn": "2018-05-04T17:42:33Z",
      "side": 1,
      "message": "actual_next_commit_position",
      "range": {
        "startLine": 142,
        "startChar": 16,
        "endLine": 142,
        "endChar": 47
      },
      "revId": "fa34123fc512360c148f9b840c1b0d3a22ee39da",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}